# Zeabur Template: Frontend only (GIT service)
apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: calenote-frontend-only
  displayName: Calenote Frontend (Next.js)
  description: Frontend-only deployment using Git with monorepo rootDirectory.

spec:
  services:
    - name: frontend
      template: GIT
      git:
        url: https://github.com/WeichunK/calenote
        branch: main
        rootDirectory: packages/web
      buildCommand: cd ../.. && npm install && npm run build --workspace=web
      startCommand: cd ../.. && npm run start --workspace=web -- -p ${PORT}
      ports:
        - id: web
          port: 3000
          type: HTTP
      env:
        NEXT_PUBLIC_API_URL:
          default: https://calenote-backend.zeabur.app/api/v1
        NEXT_PUBLIC_WS_URL:
          default: wss://calenote-backend.zeabur.app/ws
        NODE_ENV:
          default: production
